# Generated by Django 3.2.12 on 2024-03-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0003_basket_gamebasket_gameuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
