# Generated by Django 3.2.12 on 2024-03-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0004_alter_game_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameBasket',
        ),
    ]
